GET http://localhost:3001/players/ HTTP/1.1
###

POST http://localhost:3001/players/ HTTP/1.1
Content-Type:  application/json

{
  "playerName": "Eswar RAO",
  "jerseyNumber": 25,
  "role": "Batter"
}
###

GET http://localhost:3001/players/6 HTTP/1.1
###

PUT http://localhost:3001/players/26 HTTP/1.1
Content-Type:  application/json

{
  "playerName": "Moneesha",
  "jerseyNumber": 24,
  "role": "All-rounder"
}
###

DELETE http://localhost:3001/players/6 HTTP/1.1
###